version: "3.9"
services:
  probien-database:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=probien
    volumes:
      - pg-data:/var/lib/postgresql/data
  probien:
    build: .
    env_file: ./vars.env
    ports:
      - "9000:9000"
    links:
      - probien-database
  redis-session:
    image: redis/redis-stack-server
    ports:
      - "6379:6379"
    volumes:
      - $PWD/configs/redis.conf:/usr/local/etc/redis/redis.conf
    links:
      - probien
volumes:
  pg-data:
