version: "3.9"
services:
  probien-database:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=probien
    volumes:
      - pg-data:/var/lib/postgresql/data
  probien:
    build: .
    env_file: ./vars.env
    ports:
      - "9000:9000"
    links:
      - probien-database
volumes:
  pg-data:
