# Get a branch office by ID
GET http://localhost:9000/probien/api/v1/branch-offices/1 HTTP/1.1
content-type: application/json

#Get all existing branch offices
GET http://localhost:9000/probien/api/v1/branch-offices/ HTTP/1.1
content-type: application/json

#Create a new branch office
POST http://localhost:9000/probien/api/v1/branch-offices/ HTTP/1.1
content-type: application/json
{
    "branch_name":"Branch Test",
    "address":"Fake address #12",
    "zip_code":"87291"
}

#Update branch (dinamic fields)
PATCH http://localhost:9000/probien/api/v1/branch-offices/ HTTP/1.1
content-type: application/json
{
	"id":1,
	"branch_name":"Branch 1"
}