# Get a category by ID
GET http://localhost:9000/probien/api/v1/categories/1 HTTP/1.1
content-type: application/json

#Get all existing categories
GET http://localhost:9000/probien/api/v1/categories/ HTTP/1.1
content-type: application/json

#Create a new category
POST http://localhost:9000/probien/api/v1/categories/ HTTP/1.1
content-type: application/json
{
	"name":"Electrodomesticos",
	"description":"solo electrodomesticos para el hogar",
	"interest_rate":0.6
}

#Delete category by ID
DELETE http://localhost:9000/probien/api/v1/categories/ HTTP/1.1
Content-Type: application/json
{
	"id":1
}

#Update category (dinamic fields)
PATCH http://localhost:9000/probien/api/v1/categories/ HTTP/1.1
content-type: application/json
{
	"id":1,
	"name": "Autos",
	"description": "categoria especial para autos"
}