# Get an employee by email
GET http://localhost:9000/probien/api/v1/employees/byEmail/ HTTP/1.1
content-type: application/json
{
	"email":"test@gmail.com"
}

#Get all existing employees
GET http://localhost:9000/probien/api/v1/employees/ HTTP/1.1
content-type: application/json

#Login
POST http://localhost:9000/probien/api/v1/employees/login HTTP/1.1
content-type: application/json
{
	"email":"test@gmail.com",
	"password":"1onjdkn1#23!?"
}

POST http://localhost:9000/probien/api/v1/employees/ HTTP/1.1
Content-Type: application/json
{
	"name":"paco",
	"first_name":"flores",
	"second_name":"flores",
	"address":"Villa nueva",
	"phone":"7774112012",
	"email":"pacof@gmail.com",
	"password":"1##!asdawaa",
	"is_admin":false,
	"is_active":true
}

#Update employee (dinamic fields)
PATCH http://localhost:9000/probien/api/v1/employees/ HTTP/1.1
content-type: application/json
{
	"id": 1,
	"branch_office_id":1
}