# Get a pawn order by ID
GET http://localhost:9000/probien/api/v1/customers/1 HTTP/1.1
content-type: application/json

#Get all existing pawn orders
GET http://localhost:9000/probien/api/v1/pawn-orders/ HTTP/1.1
content-type: application/json

#Create a new pawn order
POST http://localhost:9000/probien/api/v1/pawn-orders/ HTTP/1.1
content-type: application/json
{
	"employee_id":1,
	"customer_id":1,
	"status_id":1,
	"total_mount":1600,
	"monthly":true,
	"products":[
		{
			"category_id":1,
			"price":1500,
			"name":"TEST1",
			"brand":"other test1",
			"details":"this is a detail for a test1",
			"on_sale":false
		},
		{
			"category_id":1,
			"price":1600,
			"name":"TEST2",
			"brand":"other test2",
			"details":"this is a detail for a test2",
			"on_sale":false
		}
	]
}

#Update pawn order (dinamic fields)
PATCH http://localhost:9000/probien/api/v1/pawn-orders/ HTTP/1.1
content-type: application/json
{
	"id":1,
	"monthly":false
}